/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BridgeManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bridgeFeePercent"
      | "bridgeRequests"
      | "calculateBridgeOutput"
      | "completeBridge"
      | "conversionRates"
      | "getBalance"
      | "getBridgeRequest"
      | "getUserBridgeRequests"
      | "initiateBridge"
      | "owner"
      | "renounceOwnership"
      | "setBridgeFee"
      | "setConversionRate"
      | "setSupportedChain"
      | "supportedChains"
      | "transferOwnership"
      | "userBridgeRequests"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BridgeCompleted"
      | "BridgeInitiated"
      | "ChainAdded"
      | "ConversionRateUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bridgeFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeRequests",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateBridgeOutput",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "completeBridge",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "conversionRates",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBridgeRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBridgeRequests",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateBridge",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBridgeFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setConversionRate",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSupportedChain",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedChains",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userBridgeRequests",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "bridgeFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bridgeRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateBridgeOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "conversionRates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBridgeRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBridgeRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBridgeFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setConversionRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSupportedChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedChains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userBridgeRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace BridgeCompletedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    user: AddressLike,
    outputAmount: BigNumberish,
    success: boolean
  ];
  export type OutputTuple = [
    requestId: string,
    user: string,
    outputAmount: bigint,
    success: boolean
  ];
  export interface OutputObject {
    requestId: string;
    user: string;
    outputAmount: bigint;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeInitiatedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    user: AddressLike,
    amount: BigNumberish,
    targetChain: string,
    targetToken: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    user: string,
    amount: bigint,
    targetChain: string,
    targetToken: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: string;
    user: string;
    amount: bigint;
    targetChain: string;
    targetToken: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainAddedEvent {
  export type InputTuple = [chain: string, supported: boolean];
  export type OutputTuple = [chain: string, supported: boolean];
  export interface OutputObject {
    chain: string;
    supported: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConversionRateUpdatedEvent {
  export type InputTuple = [tokenSymbol: string, rate: BigNumberish];
  export type OutputTuple = [tokenSymbol: string, rate: bigint];
  export interface OutputObject {
    tokenSymbol: string;
    rate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BridgeManager extends BaseContract {
  connect(runner?: ContractRunner | null): BridgeManager;
  waitForDeployment(): Promise<this>;

  interface: BridgeManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bridgeFeePercent: TypedContractMethod<[], [bigint], "view">;

  bridgeRequests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, string, bigint, boolean, string] & {
        user: string;
        amount: bigint;
        targetChain: string;
        targetToken: string;
        timestamp: bigint;
        isCompleted: boolean;
        requestId: string;
      }
    ],
    "view"
  >;

  calculateBridgeOutput: TypedContractMethod<
    [inputAmount: BigNumberish, targetToken: string],
    [[bigint, bigint] & { outputAmount: bigint; fee: bigint }],
    "view"
  >;

  completeBridge: TypedContractMethod<
    [requestId: BytesLike],
    [void],
    "nonpayable"
  >;

  conversionRates: TypedContractMethod<[arg0: string], [bigint], "view">;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getBridgeRequest: TypedContractMethod<
    [requestId: BytesLike],
    [
      [string, bigint, string, string, bigint, boolean] & {
        user: string;
        amount: bigint;
        targetChain: string;
        targetToken: string;
        timestamp: bigint;
        isCompleted: boolean;
      }
    ],
    "view"
  >;

  getUserBridgeRequests: TypedContractMethod<
    [user: AddressLike],
    [string[]],
    "view"
  >;

  initiateBridge: TypedContractMethod<
    [targetChain: string, targetToken: string],
    [string],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setBridgeFee: TypedContractMethod<
    [newFeePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  setConversionRate: TypedContractMethod<
    [tokenSymbol: string, rate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSupportedChain: TypedContractMethod<
    [chain: string, supported: boolean],
    [void],
    "nonpayable"
  >;

  supportedChains: TypedContractMethod<[arg0: string], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userBridgeRequests: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  withdrawFees: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bridgeFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bridgeRequests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, string, bigint, boolean, string] & {
        user: string;
        amount: bigint;
        targetChain: string;
        targetToken: string;
        timestamp: bigint;
        isCompleted: boolean;
        requestId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateBridgeOutput"
  ): TypedContractMethod<
    [inputAmount: BigNumberish, targetToken: string],
    [[bigint, bigint] & { outputAmount: bigint; fee: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "completeBridge"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "conversionRates"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBridgeRequest"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [
      [string, bigint, string, string, bigint, boolean] & {
        user: string;
        amount: bigint;
        targetChain: string;
        targetToken: string;
        timestamp: bigint;
        isCompleted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBridgeRequests"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "initiateBridge"
  ): TypedContractMethod<
    [targetChain: string, targetToken: string],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBridgeFee"
  ): TypedContractMethod<[newFeePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setConversionRate"
  ): TypedContractMethod<
    [tokenSymbol: string, rate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSupportedChain"
  ): TypedContractMethod<
    [chain: string, supported: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportedChains"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userBridgeRequests"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BridgeCompleted"
  ): TypedContractEvent<
    BridgeCompletedEvent.InputTuple,
    BridgeCompletedEvent.OutputTuple,
    BridgeCompletedEvent.OutputObject
  >;
  getEvent(
    key: "BridgeInitiated"
  ): TypedContractEvent<
    BridgeInitiatedEvent.InputTuple,
    BridgeInitiatedEvent.OutputTuple,
    BridgeInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "ChainAdded"
  ): TypedContractEvent<
    ChainAddedEvent.InputTuple,
    ChainAddedEvent.OutputTuple,
    ChainAddedEvent.OutputObject
  >;
  getEvent(
    key: "ConversionRateUpdated"
  ): TypedContractEvent<
    ConversionRateUpdatedEvent.InputTuple,
    ConversionRateUpdatedEvent.OutputTuple,
    ConversionRateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BridgeCompleted(bytes32,address,uint256,bool)": TypedContractEvent<
      BridgeCompletedEvent.InputTuple,
      BridgeCompletedEvent.OutputTuple,
      BridgeCompletedEvent.OutputObject
    >;
    BridgeCompleted: TypedContractEvent<
      BridgeCompletedEvent.InputTuple,
      BridgeCompletedEvent.OutputTuple,
      BridgeCompletedEvent.OutputObject
    >;

    "BridgeInitiated(bytes32,address,uint256,string,string,uint256)": TypedContractEvent<
      BridgeInitiatedEvent.InputTuple,
      BridgeInitiatedEvent.OutputTuple,
      BridgeInitiatedEvent.OutputObject
    >;
    BridgeInitiated: TypedContractEvent<
      BridgeInitiatedEvent.InputTuple,
      BridgeInitiatedEvent.OutputTuple,
      BridgeInitiatedEvent.OutputObject
    >;

    "ChainAdded(string,bool)": TypedContractEvent<
      ChainAddedEvent.InputTuple,
      ChainAddedEvent.OutputTuple,
      ChainAddedEvent.OutputObject
    >;
    ChainAdded: TypedContractEvent<
      ChainAddedEvent.InputTuple,
      ChainAddedEvent.OutputTuple,
      ChainAddedEvent.OutputObject
    >;

    "ConversionRateUpdated(string,uint256)": TypedContractEvent<
      ConversionRateUpdatedEvent.InputTuple,
      ConversionRateUpdatedEvent.OutputTuple,
      ConversionRateUpdatedEvent.OutputObject
    >;
    ConversionRateUpdated: TypedContractEvent<
      ConversionRateUpdatedEvent.InputTuple,
      ConversionRateUpdatedEvent.OutputTuple,
      ConversionRateUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
