/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GasManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ALLOCATION_TIMEOUT"
      | "allocateGas"
      | "allocations"
      | "forceRevertExpired"
      | "fundPool"
      | "getAllocation"
      | "maxAllocationPerUser"
      | "owner"
      | "poolBalance"
      | "renounceOwnership"
      | "returnGas"
      | "revertGas"
      | "setMaxAllocationPerUser"
      | "transferOwnership"
      | "updateEligibility"
      | "userActiveAllocation"
      | "userEligibleAmount"
      | "withdrawFromPool"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EligibilityUpdated"
      | "GasAllocated"
      | "GasReverted"
      | "OwnershipTransferred"
      | "PoolFunded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ALLOCATION_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allocateGas",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allocations",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "forceRevertExpired",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "fundPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllocation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxAllocationPerUser",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "returnGas",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revertGas",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxAllocationPerUser",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEligibility",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userActiveAllocation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userEligibleAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFromPool",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ALLOCATION_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allocateGas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allocations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceRevertExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxAllocationPerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "returnGas", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revertGas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxAllocationPerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userActiveAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userEligibleAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFromPool",
    data: BytesLike
  ): Result;
}

export namespace EligibilityUpdatedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GasAllocatedEvent {
  export type InputTuple = [
    allocationId: BytesLike,
    user: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    allocationId: string,
    user: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    allocationId: string;
    user: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GasRevertedEvent {
  export type InputTuple = [
    allocationId: BytesLike,
    user: AddressLike,
    amount: BigNumberish,
    successful: boolean
  ];
  export type OutputTuple = [
    allocationId: string,
    user: string,
    amount: bigint,
    successful: boolean
  ];
  export interface OutputObject {
    allocationId: string;
    user: string;
    amount: bigint;
    successful: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolFundedEvent {
  export type InputTuple = [funder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [funder: string, amount: bigint];
  export interface OutputObject {
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GasManager extends BaseContract {
  connect(runner?: ContractRunner | null): GasManager;
  waitForDeployment(): Promise<this>;

  interface: GasManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ALLOCATION_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  allocateGas: TypedContractMethod<[user: AddressLike], [string], "nonpayable">;

  allocations: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean, string] & {
        user: string;
        amount: bigint;
        timestamp: bigint;
        isActive: boolean;
        transactionHash: string;
      }
    ],
    "view"
  >;

  forceRevertExpired: TypedContractMethod<
    [allocationId: BytesLike],
    [void],
    "nonpayable"
  >;

  fundPool: TypedContractMethod<[], [void], "payable">;

  getAllocation: TypedContractMethod<
    [allocationId: BytesLike],
    [
      [string, bigint, bigint, boolean] & {
        user: string;
        amount: bigint;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  maxAllocationPerUser: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  poolBalance: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  returnGas: TypedContractMethod<[allocationId: BytesLike], [void], "payable">;

  revertGas: TypedContractMethod<
    [allocationId: BytesLike],
    [void],
    "nonpayable"
  >;

  setMaxAllocationPerUser: TypedContractMethod<
    [newMax: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateEligibility: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  userActiveAllocation: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  userEligibleAmount: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  withdrawFromPool: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ALLOCATION_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allocateGas"
  ): TypedContractMethod<[user: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "allocations"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean, string] & {
        user: string;
        amount: bigint;
        timestamp: bigint;
        isActive: boolean;
        transactionHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "forceRevertExpired"
  ): TypedContractMethod<[allocationId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundPool"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getAllocation"
  ): TypedContractMethod<
    [allocationId: BytesLike],
    [
      [string, bigint, bigint, boolean] & {
        user: string;
        amount: bigint;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxAllocationPerUser"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "returnGas"
  ): TypedContractMethod<[allocationId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "revertGas"
  ): TypedContractMethod<[allocationId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxAllocationPerUser"
  ): TypedContractMethod<[newMax: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateEligibility"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userActiveAllocation"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "userEligibleAmount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawFromPool"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "EligibilityUpdated"
  ): TypedContractEvent<
    EligibilityUpdatedEvent.InputTuple,
    EligibilityUpdatedEvent.OutputTuple,
    EligibilityUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GasAllocated"
  ): TypedContractEvent<
    GasAllocatedEvent.InputTuple,
    GasAllocatedEvent.OutputTuple,
    GasAllocatedEvent.OutputObject
  >;
  getEvent(
    key: "GasReverted"
  ): TypedContractEvent<
    GasRevertedEvent.InputTuple,
    GasRevertedEvent.OutputTuple,
    GasRevertedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolFunded"
  ): TypedContractEvent<
    PoolFundedEvent.InputTuple,
    PoolFundedEvent.OutputTuple,
    PoolFundedEvent.OutputObject
  >;

  filters: {
    "EligibilityUpdated(address,uint256)": TypedContractEvent<
      EligibilityUpdatedEvent.InputTuple,
      EligibilityUpdatedEvent.OutputTuple,
      EligibilityUpdatedEvent.OutputObject
    >;
    EligibilityUpdated: TypedContractEvent<
      EligibilityUpdatedEvent.InputTuple,
      EligibilityUpdatedEvent.OutputTuple,
      EligibilityUpdatedEvent.OutputObject
    >;

    "GasAllocated(bytes32,address,uint256,uint256)": TypedContractEvent<
      GasAllocatedEvent.InputTuple,
      GasAllocatedEvent.OutputTuple,
      GasAllocatedEvent.OutputObject
    >;
    GasAllocated: TypedContractEvent<
      GasAllocatedEvent.InputTuple,
      GasAllocatedEvent.OutputTuple,
      GasAllocatedEvent.OutputObject
    >;

    "GasReverted(bytes32,address,uint256,bool)": TypedContractEvent<
      GasRevertedEvent.InputTuple,
      GasRevertedEvent.OutputTuple,
      GasRevertedEvent.OutputObject
    >;
    GasReverted: TypedContractEvent<
      GasRevertedEvent.InputTuple,
      GasRevertedEvent.OutputTuple,
      GasRevertedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolFunded(address,uint256)": TypedContractEvent<
      PoolFundedEvent.InputTuple,
      PoolFundedEvent.OutputTuple,
      PoolFundedEvent.OutputObject
    >;
    PoolFunded: TypedContractEvent<
      PoolFundedEvent.InputTuple,
      PoolFundedEvent.OutputTuple,
      PoolFundedEvent.OutputObject
    >;
  };
}
