/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface QuestHubInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addLevelThreshold"
      | "completeQuest"
      | "createQuest"
      | "gasManager"
      | "getLevelThresholds"
      | "getQuest"
      | "getTotalQuests"
      | "getUserProgress"
      | "hasCompletedQuest"
      | "levelThresholds"
      | "owner"
      | "questCounter"
      | "quests"
      | "renounceOwnership"
      | "setGasManager"
      | "toggleQuestStatus"
      | "transferOwnership"
      | "userProgress"
      | "verifyAndCompleteQuest"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LevelUp"
      | "OwnershipTransferred"
      | "QuestCompleted"
      | "QuestCreated"
      | "RewardClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addLevelThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeQuest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createQuest",
    values: [string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gasManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLevelThresholds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getQuest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalQuests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserProgress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasCompletedQuest",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "levelThresholds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "questCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGasManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleQuestStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userProgress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyAndCompleteQuest",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addLevelThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gasManager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLevelThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getQuest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalQuests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasCompletedQuest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "levelThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "questCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleQuestStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyAndCompleteQuest",
    data: BytesLike
  ): Result;
}

export namespace LevelUpEvent {
  export type InputTuple = [
    user: AddressLike,
    newLevel: BigNumberish,
    totalXP: BigNumberish
  ];
  export type OutputTuple = [user: string, newLevel: bigint, totalXP: bigint];
  export interface OutputObject {
    user: string;
    newLevel: bigint;
    totalXP: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestCompletedEvent {
  export type InputTuple = [
    user: AddressLike,
    questId: BigNumberish,
    xpEarned: BigNumberish,
    gasEligibilityEarned: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    questId: bigint,
    xpEarned: bigint,
    gasEligibilityEarned: bigint
  ];
  export interface OutputObject {
    user: string;
    questId: bigint;
    xpEarned: bigint;
    gasEligibilityEarned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestCreatedEvent {
  export type InputTuple = [
    questId: BigNumberish,
    name: string,
    xpReward: BigNumberish,
    gasReward: BigNumberish
  ];
  export type OutputTuple = [
    questId: bigint,
    name: string,
    xpReward: bigint,
    gasReward: bigint
  ];
  export interface OutputObject {
    questId: bigint;
    name: string;
    xpReward: bigint;
    gasReward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface QuestHub extends BaseContract {
  connect(runner?: ContractRunner | null): QuestHub;
  waitForDeployment(): Promise<this>;

  interface: QuestHubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addLevelThreshold: TypedContractMethod<
    [xpRequired: BigNumberish],
    [void],
    "nonpayable"
  >;

  completeQuest: TypedContractMethod<
    [questId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createQuest: TypedContractMethod<
    [
      name: string,
      description: string,
      xpReward: BigNumberish,
      gasReward: BigNumberish,
      requiredAction: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  gasManager: TypedContractMethod<[], [string], "view">;

  getLevelThresholds: TypedContractMethod<[], [bigint[]], "view">;

  getQuest: TypedContractMethod<
    [questId: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, bigint] & {
        name: string;
        description: string;
        xpReward: bigint;
        gasReward: bigint;
        isActive: boolean;
        completionCount: bigint;
      }
    ],
    "view"
  >;

  getTotalQuests: TypedContractMethod<[], [bigint], "view">;

  getUserProgress: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        totalXP: bigint;
        completedQuests: bigint;
        level: bigint;
        xpToNextLevel: bigint;
      }
    ],
    "view"
  >;

  hasCompletedQuest: TypedContractMethod<
    [user: AddressLike, questId: BigNumberish],
    [boolean],
    "view"
  >;

  levelThresholds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  questCounter: TypedContractMethod<[], [bigint], "view">;

  quests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, bigint, bigint] & {
        id: bigint;
        name: string;
        description: string;
        xpReward: bigint;
        gasReward: bigint;
        isActive: boolean;
        completionCount: bigint;
        requiredAction: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setGasManager: TypedContractMethod<
    [_gasManager: AddressLike],
    [void],
    "nonpayable"
  >;

  toggleQuestStatus: TypedContractMethod<
    [questId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userProgress: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalXP: bigint;
        completedQuests: bigint;
        level: bigint;
      }
    ],
    "view"
  >;

  verifyAndCompleteQuest: TypedContractMethod<
    [user: AddressLike, questId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addLevelThreshold"
  ): TypedContractMethod<[xpRequired: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeQuest"
  ): TypedContractMethod<[questId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createQuest"
  ): TypedContractMethod<
    [
      name: string,
      description: string,
      xpReward: BigNumberish,
      gasReward: BigNumberish,
      requiredAction: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gasManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLevelThresholds"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getQuest"
  ): TypedContractMethod<
    [questId: BigNumberish],
    [
      [string, string, bigint, bigint, boolean, bigint] & {
        name: string;
        description: string;
        xpReward: bigint;
        gasReward: bigint;
        isActive: boolean;
        completionCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalQuests"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserProgress"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        totalXP: bigint;
        completedQuests: bigint;
        level: bigint;
        xpToNextLevel: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasCompletedQuest"
  ): TypedContractMethod<
    [user: AddressLike, questId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "levelThresholds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "questCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "quests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, bigint, bigint] & {
        id: bigint;
        name: string;
        description: string;
        xpReward: bigint;
        gasReward: bigint;
        isActive: boolean;
        completionCount: bigint;
        requiredAction: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGasManager"
  ): TypedContractMethod<[_gasManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "toggleQuestStatus"
  ): TypedContractMethod<[questId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userProgress"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalXP: bigint;
        completedQuests: bigint;
        level: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyAndCompleteQuest"
  ): TypedContractMethod<
    [user: AddressLike, questId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "LevelUp"
  ): TypedContractEvent<
    LevelUpEvent.InputTuple,
    LevelUpEvent.OutputTuple,
    LevelUpEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "QuestCompleted"
  ): TypedContractEvent<
    QuestCompletedEvent.InputTuple,
    QuestCompletedEvent.OutputTuple,
    QuestCompletedEvent.OutputObject
  >;
  getEvent(
    key: "QuestCreated"
  ): TypedContractEvent<
    QuestCreatedEvent.InputTuple,
    QuestCreatedEvent.OutputTuple,
    QuestCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;

  filters: {
    "LevelUp(address,uint256,uint256)": TypedContractEvent<
      LevelUpEvent.InputTuple,
      LevelUpEvent.OutputTuple,
      LevelUpEvent.OutputObject
    >;
    LevelUp: TypedContractEvent<
      LevelUpEvent.InputTuple,
      LevelUpEvent.OutputTuple,
      LevelUpEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "QuestCompleted(address,uint256,uint256,uint256)": TypedContractEvent<
      QuestCompletedEvent.InputTuple,
      QuestCompletedEvent.OutputTuple,
      QuestCompletedEvent.OutputObject
    >;
    QuestCompleted: TypedContractEvent<
      QuestCompletedEvent.InputTuple,
      QuestCompletedEvent.OutputTuple,
      QuestCompletedEvent.OutputObject
    >;

    "QuestCreated(uint256,string,uint256,uint256)": TypedContractEvent<
      QuestCreatedEvent.InputTuple,
      QuestCreatedEvent.OutputTuple,
      QuestCreatedEvent.OutputObject
    >;
    QuestCreated: TypedContractEvent<
      QuestCreatedEvent.InputTuple,
      QuestCreatedEvent.OutputTuple,
      QuestCreatedEvent.OutputObject
    >;

    "RewardClaimed(address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
  };
}
